name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: windows-latest
        defaults:
          run:
            working-directory: './ReceiptProcessor'
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GHCR_PAT}}
        
          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/tl11717/receiptprocessorimage:latest
              docker push ghcr.io/tl11717/receiptprocessorimage:latest 
